require('./config/port')
const bodyParser = require('body-parser')
const express =  require('express')
const cors = require('cors')
const app = express()

app.use(cors())
// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))
// parse application/json
app.use(bodyParser.json())

const client = require('./view/client')
//const notification = require('./util/notification')
const account  = require('./view/account')
const transaction = require('./view/transaction')
const bankcredit = require('./view/bankcredit')
const firebase = require('./view/firebase')
const bank = require('./view/bank')
const contact = require('./view/contact')
const ping = require('./view/ping')
const service = require('./view/service')
const pagofacil = require('./view/pagofacil')
const investment = require('./view/investment')
app.use(client)
app.use(account)
app.use(transaction)
app.use(bankcredit)
app.use(firebase)
app.use(bank)
app.use(contact)
app.use(ping)
app.use(service)
app.use(pagofacil)
app.use(investment)

app.listen(process.env.PORT,function () {
    console.log(`SERVER API REST ${process.env.PORT}`)
})